### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by burner1024** [AstroBryGuy/NearInfinity-OSX#1]
In my environment, for some reason no settings are saved between restarts. Every time I select chitin.key, change indent, look and feel. Upon a restart, it's not preserved.
What could be the issue?

**Comment by AstroBryGuy** [comment]
Sounds like it could be a permissions issue on your preferences file for NearInfinity. You can try going into your ~/Library/Preferences folder and deleting the org.infinity.gui.plist file. Then re-load NearInfinity, make your changes, and see if the changes stick.

**Comment by burner1024** [comment]
They don't. The file doesn't get re-created, either.

All actions are performed using a single user account, so I don't see how would permissions be different.

**Comment by burner1024** [comment]
Nevermind, I tried the upstream and it's actually the same.

**Comment by AstroBryGuy** [comment]
If the preferences file is not getting recreated, then it sounds like a permissions issue. Can you check the permissions on your ~/Library/Preferences folder? It should be read & write for user.

**Comment by burner1024** [comment]
It is all read and write. It comes up in Metal.

Anyway, like I said, I'm getting the same with original, so I opened an issue there.
